### ISSUE TITLE
Validating plans is needed

### ISSUE THREAD

**Issue by hmpf** [hmpf/easydmp#20]
Since it is now possible to skip between obligatory questions, reaching the last question no longer guarantees that all questions have been answered.

Therefore, we must manually validate a plan.

- [x] Backend support for validating is needed, issue #21 
- [x] UI to show what is validated is needed, issue #22 
- [x] Some way to mark a plan as valid is needed in the REST API, issue #23

**Comment by adilhasan** [comment]
It would be good to also keep a record of the fact that the plan editor has got sign off from the project principal investigator and perhaps the research offices (or something like that) at the participating institutes. Perhaps this should be questions in the plan.

**Comment by hmpf** [comment]
On 2018-06-06 19:51, Adil Hasan wrote:
> It would be good to also keep a record of the fact that the plan editor
> has got sign off from the project principal investigator and perhaps the
> research offices (or something like that) at the participating
> institutes. Perhaps this should be questions in the plan.

We could have that as a separate section. But I suspect that different
institutions will be doing this differently, and it is insanity to
support more than one flow at this stage. Maybe for version 3.

We need milestone tags :)

**Comment by hmpf** [comment]
I think we are not in agreement about what "validation" means here. We'll need a new issue for that.
